Algoritmo "antecessor"
// Disciplina  : Lógica de Programação com visual G
// Professor   :
// Descrição   : Ler um valor ee escrever seu antecessor.
// Autor(a)    : Grazielly De Oliveira Pereira
// Data atual  : 25/03/2026

var
   valor, antecessor: real
inicio
   escreval("=== Antecessor  de um Numero ===")
   escreva("Digite um valor: ")
   leia(valor)
   antecessor <- valor - 1
   escreval("Antecessor: ", antecessor:0:2)
fimalgoritmo
