Algoritmo "Area retangulo"
// Disciplina  :Lógica de Programação com visual G
// Professor   :Jajah do Grau
// Descrição   :Escrever um algoritimo para ler as dimensões de um retângulo.
// Autor(a)    :Grazielly De Oliveira Pereira
// Data atual  : 25/03/2026

var
   base, altura, area: real
inicio
   escreval("=== Area do Retangulo ===")
   escreva("Base: ")
   leia(base)
   escreva("Altura: ")
   leia(altura)
   area <- base * altura
   escreval("Area: ", area:0:2)
fimalgoritmo
