Algoritmo "Area do Circulo"
// Disciplina  :Lógica de Programação com visual G
// Professor   : Jajah Do Grau
// Descrição   : Algoritmo para ler o raio de um circulo e
//escrever a sua área.
// Autor(a)    : Grazielly De Oliveira Pereira
// Data atual  : 27/03/2025
Var
 raio, area: real
inicio
   escreval("=== Area do Circulo ===")
   escreva("Raio: ")
   leia(raio)
   area <- 3.14159 * raio * raio
   escreval("Area: ", area:0:2)
fimalgoritmo
