Algoritmo "Area do Quadrado e Dobro"
// Disciplina  :Lógica de Programação com visual G
// Professor   : Jajah Do Grau
// Descrição   : Algoritimo que calcula a aréa do quadrado e o dobro.
// Autor(a)    : Grazielly De Oliveira Pereira
// Data atual  : 25/03/2025
Var
 lado, area, dobro: real
inicio
   escreval("=== Area do Quadrado e Dobro ===")
   escreva("Lado do quadrado: ")
   leia(lado)
   area <- lado * lado
   dobro <- area * 2
   escreval("Area: ", area:0:2)
   escreval("Dobro da area: ", dobro:0:2)
fimalgoritmo
