Algoritmo "Dois Valores"
// Disciplina  :Lógica de Programação com visual G
// Professor   : Jajah Do Grau
// Descrição   : Ler maior de dois valores.
// Autor(a)    : Grazielly De Oliveira Pereira
// Data atual  : 30/03/2025
Var
 a, b: real
inicio
   escreval("=== Maior de Dois Valores ===")
   escreva("Primeiro valor: ")
   leia(a)
   escreva("Segundo valor: ")
   leia(b)
   se a > b entao
      escreval("Maior: ", a:0:2)
   senao
      escreval("Maior: ", b:0:2)
   fimse
fimalgoritmo
