Algoritmo "Dois Valores em Ordem Crescente"
// Disciplina  :Lógica de Programação com visual G
// Professor   : Jajah Do Grau
// Autor(a)    : Grazielly De Oliveira Pereira
// Data atual  : 30/03/2025
Var               a, b: real
inicio
   escreval("=== Dois Valores em Ordem Crescente ===")
   escreva("Primeiro valor: ")
   leia(a)
   escreva("Segundo valor: ")
   leia(b)
   se a > b entao
      escreval(b:0:2, "  ", a:0:2)
   senao
      escreval(a:0:2, "  ", b:0:2)
   fimse
fimalgoritmo
