Algoritmo "Fahrenheit para Celsius"
// Disciplina  :Lógica de Programação com visual G
// Professor   : Jajah Do Grau
// Descrição   :
// Autor(a)    : Grazielly De Oliveira Pereira
// Data atual  : 27/03/2025
Var
F, C: real
inicio
   escreval("=== Fahrenheit para Celsius ===")
   escreva("Temperatura em Fahrenheit: ")
   leia(F)
   C <- 5 * (F - 32) / 9
   escreval("Temperatura em Celsius: ", C:0:2)
fimalgoritmo
