Algoritmo "Positivo ou Negativo"
// Disciplina  : Lógica de Programação com visual G
// Professor   : Jajah Do Grau
// Descrição   : Algoritmo que mostra se o numero é positivo ou negativo.
// Autor(a)    : Grazielly De Oliveira Pereira
// Data atual  : 27/03/2025
Var
valor: real
inicio
   escreval("=== Positivo ou Negativo ===")
   escreva("Digite um valor: ")
   leia(valor)
   se valor >= 0 entao
      escreval("Positivo")
   senao
      escreval("Negativo")
   fimse
fimalgoritmo
