Algoritmo "Valor positivo ou negativo"
// Disciplina  :Lógica de Programação com visual G
// Professor   : Jajah Do Grau
// Autor(a)    : Grazielly De Oliveira Pereira
// Data atual  : 30/03/2025
Var
valor: real
inicio
   escreva("Valor: ")
   leia(valor)
   se valor > 0 entao
      escreval("Positivo")
   senao
      se valor < 0 entao
         escreval("Negativo")
      senao
         escreval("Zero")
      fimse
   fimse
fimalgoritmo
